- id: jupyter-julia-format
  name: format julia code within jupyter
  description: see name
  language: system
  files: \.ipynb$
  entry: |
    julia -e '
    using JSON
    using JuliaFormatter

    function format_notebook(file)
        local notebook
        try
            # Parse the notebook JSON
            notebook = JSON.parsefile(file)
        catch e
            println("Error parsing JSON file: $file")
            println("Reason: ", e)
            exit(1)
        end

        for cell in notebook["cells"]
            if cell["cell_type"] == "code" 
                # Format the code in the cell
                formatted_code = format_text(join(cell["source"]), BlueStyle())
                cell["source"] = split(formatted_code, '\n')
            end
        end

        # Save the formatted notebook
        open(file, "w") do io
            JSON.print(io, notebook)
        end
        println("Formatted notebook: $file")
    end

    # Run the formatter on the provided file
    if length(ARGS) > 0
        format_notebook(ARGS[1])
        exit(0)
    else
        println("No file provided to format.")
        exit(0)
    end'